type = "card"
title = "Awards and Grants"
# description = "Honors and awards I have received."

[[items]]
title = "Digital Communication Methods Lab Thesis Grant"
subtitle = "Amsterdam School of Communication Research, University of Amsterdam"
date = "2025"
link = "https://digicomlab.github.io/thesisgrant/theses/2025_zhao/"

[[items]]
title = "International Conference on Research in Advertising (ICORIA) Student Grant"
subtitle = "European Advertising Academy"
date = "2025"
link = "https://www.europeanadvertisingacademy.org/winners-of-the-icoria-student-grant-2025/"

[[items]]
title = "China National Scholarship"
subtitle = "Ministry of Education of the People's Republic of China"
date = "2021"

[[items]]
title = "Zhejiang Provincial Government Scholarship" 
subtitle = "The People's Government of Zhejiang Province"
date = "2019-2020"

[[items]]
title = "Undergraduate Academic Scholarship" 
subtitle = "China Jiliang University"
date = "2018-2022"
