[[news]]
date = "2026-05"
content = "Joined the European Advertising Academy Communication Committee"

[[news]]
date = "2026-04"
content = "A paper accepted by ICORIA 2026 Conference (Barcelona, Spain)"

[[news]]
date = "2026-02"
content = "Graduated as Master in Science with Cum Laude Distinction and started my PhD at the University of Amsterdam 🎉"

[[news]]
date = "2026-01"
content = "Work accepted by ICA 2026 Conference (Cape Town, South Africa)"

[[news]]
date = "2026-01"
content = "Work accepted by Etmaal 2026 Conference (Papendal, Arnhem, the Netherlands)"

[[news]]
date = "2025-11"
content = "Received Digital Communication Methods Lab Thesis Grant for my Research Master's Thesis"

[[news]]
date = "2025-06"
content = "Received International Conference on Research in Advertising (ICORIA) Student Grant as one of the two recipients"